# Numpy
 
## Numpy is a general - purpose array processing package.
### -  provides a high-performance multidimensional array object, and tools for working with these arrays.
### -  is the fundamental package for specific computing with python 

# what is an Array
### - An Array is a data Structure that store value of same datatype.
### - In python  this is main difference between  arrays and lists
### While python lists can contain values Corresponding to different datatypes,
   
  ### Array in python can only contain values  corresponding to some data type"

# How to install numpy
# if in cmd < pip install numpy> 
if in Anoconda < conda install numpy>
to check the version of numpy 

In [2]:
import numpy
print(numpy.__version__)

1.19.5


In [12]:
# verify numpy version 

# if numpy is installed in your System 

In [2]:
a=[]
print(a)
print(type(a))

[]
<class 'list'>


In [3]:
a=[1,2,3,4,5]
print(a)

[1, 2, 3, 4, 5]


In [4]:
type(a)

list

In [3]:
# import numpy
import numpy as np

In [7]:
my_list=[1,2,3,4,5]
type(my_list)

list

In [9]:
arr=np.array(my_list)
print(arr)

[1 2 3 4 5]


In [10]:
type(arr)

numpy.ndarray

In [16]:
arr # one dimensional array

array([1, 2, 3, 4, 5])

In [13]:
arr.shape

(5,)

In [17]:
arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [2]:
# let us create multi dimensional array
import numpy as np
my_list1=[1,2,3,4,5]
my_list2=[2,3,4,5,6]
my_list3=[9,7,6,8,9]
arr=np.array([my_list1,my_list2,my_list3])
print(arr)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [3]:
type(my_list1)

list

In [4]:
arr.shape

(3, 5)

In [10]:
arr.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [12]:
arr[:,:] # Slicing operation

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [15]:
arr[:,0:3]

array([[1, 2, 3],
       [2, 3, 4],
       [9, 7, 6]])

In [16]:
a=np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [21]:
a=np.arange(0,10).reshape(2,5)
b=np.arange(0,10).reshape(2,5)
c=a*b
print(c)
print(type(c))

[[ 0  1  4  9 16]
 [25 36 49 64 81]]
<class 'numpy.ndarray'>


In [20]:
arr.shape

(3, 5)

In [19]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9]])

In [25]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

# arr.shape

In [2]:
import numpy as np

In [3]:
# When ever you learn about any data structure , you learn about array,data frames,
# How we can reterieve the data inside  an array

# INDEXING  Array indexing start[0-9]
# accesing the  array elements
arr=np.array([1,2,3,4,5,6,7,8,9]) # simple array
arr.shape

(9,)

In [4]:
arr[4]

5

In [26]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
type(arr)

numpy.ndarray

In [7]:
# in array we have two important component
# Row index and column index
# indexing happens in two dimensions
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [13]:
arr[0:2,1:4]

array([[2, 3, 4],
       [3, 4, 5]])

In [41]:
#arr[:3,4:]

In [46]:
arr[:,0:5]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [39]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [36]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

In [23]:
arr1=np.arange(0,8)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
arr2=np.arange(0,8,step=2)
arr2

array([0, 2, 4, 6])

In [39]:
np.linspace(1,10,50) # uses in Deep learning to pick quickly

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [26]:
# copy
arr=np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
arr1=arr # array is an reference type

In [55]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr1[3:7]=500
print(arr1)

[  1   2   3 500 500 500 500   8   9]


In [57]:
arr

array([  1,   2,   3, 500, 500, 500, 500,   8,   9])

In [52]:
arr1=arr.copy()

In [53]:
print(arr)

[  1   2   3 500 500 500 500 500 500]


In [54]:
arr1[3:]=1000
print(arr1)

[   1    2    3 1000 1000 1000 1000 1000 1000]


In [55]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [56]:
arr1

array([   1,    2,    3, 1000, 1000, 1000, 1000, 1000, 1000])

In [40]:
# some conditions very useful in Exploratory DAtaAnalysis(EDA)
val=10
arr[arr<val]

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 9, 7, 6, 8, 9])

In [14]:
# create array and shape 
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
arr1=np.arange(0,10).reshape(2,5)
arr2=np.arange(0,10).reshape(2,5)

In [5]:
c=arr1*arr2
print(c)

[[ 0  1  4  9 16]
 [25 36 49 64 81]]


In [63]:
type(c)

numpy.ndarray

In [18]:
np.ones(7,dtype=str)

array(['1', '1', '1', '1', '1', '1', '1'], dtype='<U1')

In [61]:
np.ones(4)

array([1., 1., 1., 1.])

In [63]:
# random distribution
np.random.rand(3,3)

array([[0.66052715, 0.09454234, 0.44419224],
       [0.60058751, 0.80134557, 0.97934608],
       [0.50331095, 0.56399499, 0.61801945]])

In [66]:
arr_ex=np.random.rand(4,4)
print(arr_ex)

[[0.53247904 0.31937026 0.41493677 0.68834178]
 [0.1994773  0.61054514 0.67246649 0.49646091]
 [0.7659551  0.91265821 0.72217747 0.24162876]
 [0.27326869 0.04835477 0.77919997 0.5706365 ]]


There are
# two main reasons why 
# we would use NumPy array instead of lists in Python. 
# These reasons are:

# Less memory usage: The Python NumPy array consumes 
# less memory than lists.
# Less execution time: The NumPy array is pretty fast in terms
# of execution, as compared to lists in Python.

# Less memory usage

In [27]:
import sys

list_array = [i for i in range(100)]

print("Length of List array: ",len(list_array))

print("Type of array: ",type(list_array))

print("Memory consumption by an element in the array: ",
        sys.getsizeof(list_array[0]))

print("Memory usage by list array: ",
        (sys.getsizeof(list_array[0]))*len(list_array))

Length of List array:  100
Type of array:  <class 'list'>
Memory consumption by an element in the array:  24
Memory usage by list array:  2400


In [2]:
import numpy as np

numpy_array = np.arange(100)

print("Length of NumPy array: ",len(numpy_array))

print("Type of array: ",type(numpy_array))

print("Memory consumption by an element in the array: ",
        numpy_array.itemsize)

print("Memory usage by list array: ",
        numpy_array.itemsize*numpy_array.size)

Length of NumPy array:  100
Type of array:  <class 'numpy.ndarray'>
Memory consumption by an element in the array:  4
Memory usage by list array:  400


# Less execution time

In [3]:
import time
import numpy as np

list_array1 = [i for i in range(1000000)]
list_array2 = [i for i in range(1000000)]

start_time = time.time()
list_multiply = [list_array1[i] * list_array2[i] 
                  for i in range(1000000)]
final_time = time.time()

print("Time taken by Lists to perform multiplication: ",
      (round((final_time - start_time), 2)), "millisecond")

numpy_array1 = np.arange(1000000)
numpy_array2 = np.arange(1000000)

start_time = time.time()
numpy_multiply = numpy_array1 * numpy_array2
final_time = time.time()

print("Time taken by Lists to perform multiplication: ",
      (round((final_time - start_time), 2)), "millisecond")

Time taken by Lists to perform multiplication:  0.09 millisecond
Time taken by Lists to perform multiplication:  0.0 millisecond


Explanation

From lines 4 to 13, we created two List arrays and then performed multiplication between those two arrays. Then, we calculated the execution time.

Similarly from lines 15 to 23, we created two NumPy arrays and performed multiplication between them. Then, we calculated the execution time.