# Linear Regression in Python

# Regression

# When Do You Need Regression?

# Implementing Linear Regression in Python

In [5]:
import numpy as np
from sklearn.linear_model import LinearRegression
#The class 
#sklearn.linear_model.LinearRegression will be used to perform
#linear and polynomial regression and make predictions accordingly.

In [6]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])#The inputs (regressors, 𝑥) and output (predictor, 𝑦) 
#should be arrays (the instances of the class numpy.ndarray) 

In [7]:
print(x)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [8]:
print(y)

[ 5 20 14 32 22 38]


# Create a model and fit it

In [10]:
model = LinearRegression()

In [11]:
#First, you need to call .fit() on model
model.fit(x, y)

LinearRegression()

In [12]:
model = LinearRegression().fit(x, y)

In [13]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7158756137479542


In [14]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [15]:
 print('slope:', model.coef_)

slope: [0.54]


In [16]:
 y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [17]:
y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]
